Hotfix with a sanity test for api-gateway (#2251)
### What's done:

- fixed gateway typo
- due to the change in snakeyaml API (2.0), api-gateway is not able to start: Caused by: java.lang.NoSuchMethodError: org.yaml.snakeyaml.constructor.SafeConstructor: method 'void <init>()' not found